### ISSUE TITLE
throwing source doesn't exist

### ISSUE THREAD

**Issue by oreporan** [rmariuzzo/markdown-swagger#3]
Hey
would love to use this - 
However I'm getting

```
 [ERROR] 2019-05-06T22:16:02.836Z +1.56s Error: /.../swagger.yaml doesn't exist
    at fs.readFile.then.catch (/...markdown-swagger/index.js:100:15)
```

**Comment by CSBaum** [comment]
Any idea on how to get around this?

**Comment by oreporan** [comment]
Yes
Use this :)

https://github.com/syroegkin/swagger-markdown

Works like a charm

**Comment by calimpio** [comment]
This is better!

https://github.com/code-cy/docfast-js
